/*
  Runtime for for running assembly code generated by the compiler
*/

#include<stdio.h>
#include "convert.h"
#include "lisp.h"
#include<stdlib.h>
int entry();


int main(int argc, char* argv[]){
        struct node* nd = l_h_node(entry());
        pprint(nd);
        free(nd);
        return 0;
}
